version: '3.8'
services:
  web:
    build:
      context: ./project
      dockerfile: Dockerfile
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - ENVIRONMENT=dev
      - TESTING=1
    volumes:
      - ./project/app:/usr/src/app
    ports:
      - "8004:8000"
    entrypoint: ["uvicorn", "main:app", "--workers", "1", "--host", "0.0.0.0", "--reload"]
